### PR TITLE
add directory parser

### PR DESCRIPTION
**Pull request by alphaleadership**
to scan full directory

### CODE REVIEW

**Comment by alphaleadership** [comment]
is easy to update

**Comment by vladmandic** [comment]
- remove `yarn.lock`
- clean up non-english text
- remove hard-coded paths (`d:\\perso\\img-test\\image\\cosplay`)
- remove 3rd party dependencies (i don't even know what is `deduplicator-alphaleadershipv1`)
- make all paths not windows specific
- do not include sample output photo in your pr

**Comment by alphaleadership** [comment]
what is need to close this pr

**Comment by alphaleadership** [comment]
you dont merge

**Comment by vladmandic** [comment]
i don't understand why did you create this pr - as it looks, this is your private code.

**Comment by alphaleadership** [comment]
no is public code

**Comment by alphaleadership** [comment]
but y use for my private usage

**Pull request closed without merging**
